#!/bin/bash
# reset.sh — Reset generated layers to empty template state
# Usage: ./scripts/reset.sh [--work|--output|--all]
#
# --work    Reset 02_Work/ only
# --output  Reset 03_Outputs/ only
# --all     Reset both (default)
#
# Preserves: 01_Sources/, engine files, _README.md, .gitkeep, _custom/

set -euo pipefail

SCOPE="${1:---all}"

case "$SCOPE" in
  --work|--output|--all) ;;
  *)
    echo "Usage: ./scripts/reset.sh [--work|--output|--all]"
    exit 1
    ;;
esac

# Derive project root from script location
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PROJECT=$(cd "$SCRIPT_DIR/.." && pwd)

WORK="$PROJECT/02_Work"
OUTPUTS="$PROJECT/03_Outputs"

# --- Reset Work Layer ---
reset_work() {
  echo "Resetting 02_Work/..."

  # INSIGHTS_GRAPH.md
  cat > "$WORK/INSIGHTS_GRAPH.md" << 'TEMPLATE'
# Insights Graph

Atomic verified insights extracted from sources. Each insight has a unique `[IG-XX]` ID, a status, and a traceable source reference.

## Status Legend

- **PENDING** — Extracted but not yet verified or cross-referenced.
- **VERIFIED** — Confirmed through cross-referencing or user validation.
- **FROZEN** — Valid but deprioritized for current scope.
- **INVALIDATED** — Contradicted by stronger evidence; no longer active.
- **MERGED** — Combined with another insight during conflict resolution.
- **SUPERSEDED** — Replaced by a newer, more complete insight.

---

<!-- New insights are appended below by /analyze -->
TEMPLATE

  # CONFLICTS.md
  cat > "$WORK/CONFLICTS.md" << 'TEMPLATE'
# Conflicts Log

Contradictions detected between insights. Each conflict has a unique `[CF-XX]` ID and must be resolved through `/spec` before the specification can be updated.

## Status Legend

- **PENDING** — Detected but not yet resolved.
- **RESOLVED** — User has provided a resolution direction.

---

<!-- New conflicts are appended below by /analyze -->
TEMPLATE

  # STRATEGIC_VISION.md
  cat > "$WORK/STRATEGIC_VISION.md" << 'TEMPLATE'
# Strategic Vision

The product's strategic layer. Every decision here traces back to verified insights in `INSIGHTS_GRAPH.md`.

## Product Vision

> [To be defined after initial source analysis. Reference [IG-XX] insights.]

## Product Strategy

> [Market positioning, differentiation, business model. Reference [IG-XX] insights.]

## Design Principles

<!-- Transversal decision criteria. Each declares where it operates.
     ### [principle name]
     - **Operates at:** Strategic / Structural / Behavioral / Materialization
     - **Description:** ...
     - **Refs:** [IG-XX]
-->

## Operational Domains

<!-- High-level functional territory groupings.
     ### [domain name]
     - **Lead pillar:** [principle name]
     - **Refs:** [IG-XX]
-->

## Value Propositions

<!-- User outcomes grounded in insights. -->

## Open Questions

- [ ] What are the core user needs? (Run `/analyze` on initial sources)
- [ ] What technical constraints exist?
- [ ] What business goals drive prioritization?
TEMPLATE

  # PROPOSALS.md
  cat > "$WORK/PROPOSALS.md" << 'TEMPLATE'
# Design Proposals

Design decisions organized by operational domain. Each proposal traces back to verified insights.

<!-- Format:
     ## Domain: [domain name]

     ### [DP-XX] [Name]
     **Type:** module | feature
     **Domain:** [domain name]
     **Status:** PROPOSED | VALIDATED | BUILDING | SHIPPED
     **Grounded in:** [IG-XX], [IG-XX]
     **Parent:** [DP-XX] (features point to their module)
     **Design implications:**
     - ...
     **Acceptance criteria:**
     - ...
     **Open questions:**
     - ...
-->
TEMPLATE

  # EXTRACTIONS.md
  cat > "$WORK/EXTRACTIONS.md" << 'TEMPLATE'
# Extractions

Raw claims extracted from sources by `/extract`. Input for `/analyze`.

---

<!-- Extraction sections appended below by /extract -->
TEMPLATE

  # RESEARCH_BRIEF.md
  cat > "$WORK/RESEARCH_BRIEF.md" << 'TEMPLATE'
# Research Brief

Auto-generated narrative summary. Written by `/analyze`.

---

<!-- Content generated by /analyze -->
TEMPLATE

  # SOURCE_MAP.md
  cat > "$WORK/SOURCE_MAP.md" << 'TEMPLATE'
# Source Map

Per-file extraction state. Auto-maintained by `/extract`.

| File | Hash | Status | Timestamp |
|---|---|---|---|
TEMPLATE

  # MEMORY.md
  cat > "$WORK/MEMORY.md" << 'TEMPLATE'
# Project Memory

> Session log and state tracker. Fallback recovery when SESSION_CHECKPOINT is unavailable.
> Compacted at 80 lines — old entries summarized, 3 most recent kept in full.

## Historical Summary

<!-- Compacted summaries of past sessions appear here. -->

---

<!-- Entry format:
### YYYY-MM-DDTHH:MM — /skill or action
- **Request:** what was asked
- **Actions:** what was done
- **Result:** outcome
- **Snapshot:** sources: X | extractions: X | insights: X (V verified) | conflicts: X (P pending) | outputs: X
-->
TEMPLATE

  # Clean _temp/
  if [ -d "$WORK/_temp" ]; then
    find "$WORK/_temp" -type f -not -name '.gitkeep' -delete 2>/dev/null || true
  fi

  echo "  Restored: INSIGHTS_GRAPH.md, CONFLICTS.md, STRATEGIC_VISION.md, PROPOSALS.md"
  echo "  Restored: EXTRACTIONS.md, RESEARCH_BRIEF.md, SOURCE_MAP.md, MEMORY.md"
  echo "  Cleaned: _temp/"
}

# --- Reset Outputs Layer ---
reset_outputs() {
  echo "Resetting 03_Outputs/..."

  local deleted=0

  # Delete generated files, keep structural ones
  for f in "$OUTPUTS"/*; do
    [ -e "$f" ] || continue
    fname=$(basename "$f")

    # Skip structural files and directories
    case "$fname" in
      _README.md|.gitkeep) continue ;;
      _custom|_templates|_schemas) continue ;;
    esac

    if [ -d "$f" ]; then
      continue
    fi

    rm -f "$f"
    deleted=$((deleted + 1))
  done

  echo "  Deleted: $deleted generated file(s)"
  echo "  Preserved: _README.md, _custom/, _templates/, _schemas/"
}

# --- Execute ---
case "$SCOPE" in
  --work)
    reset_work
    ;;
  --output)
    reset_outputs
    ;;
  --all)
    reset_work
    reset_outputs
    ;;
esac

echo ""
echo "Done. Sources in 01_Sources/ are untouched."
echo "Run /analyze to rebuild the knowledge base."
